name: Release

on:
  # Trigger on any new tag that starts with "v" (e.g., v2.4.0).
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3
        with:
          # fetch-depth=0 so GoReleaser can read all tags/commits.
          fetch-depth: 0  

      # 2. Set up Go
      - uses: actions/setup-go@v4
        with:
          # This will look at your go.mod to pick the Go version, or you can hardcode e.g. "go-version: 1.20"
          go-version-file: 'go.mod'
          cache: true

      # 3. Run GoReleaser to build for multiple OS/arch and create a GitHub release
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # --clean ensures the dist/ folder is fresh each time
          args: release --clean
        env:
          # GitHub automatically sets this secret token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
