name: Release

on:
  # Trigger on any new tag that starts with "v" (e.g., v2.4.0).
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      # 2. Set up Go
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      # 3. Import GPG key
      - name: Import GPG private key
        run: |
          gpg --batch --import gpg/gpg-private.key
        env:
          GPG_TTY: $(tty)

      # 4. Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
